# -*- coding: utf-8 -*-
"""Modules  11 - 04 - 2022 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EigiVqp2DTBw1uGsACsnYaWkIePoZda7
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import math
from scipy import stats
import folium
import time
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from imblearn.over_sampling import SMOTE
import warnings
warnings.filterwarnings("ignore")
from ipywidgets import interactive
from ipywidgets import widgets
from scipy.stats import norm
import statsmodels.api as sm

from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.ensemble import RandomForestClassifier
from statsmodels.stats.outliers_influence import variance_inflation_factor